module.exports = {
    places : [{ title: 'Flughafen' , image: 'airport'} , 
    { title: 'Bank' , image: 'bank'},
    { title: 'Cemetery' , image: 'cemetery'},
    { title: 'Friedhof' , image: 'cinema'},
    { title: 'Hölle' , image: 'hell'},
    { title: 'Krankenhaus' , image: 'hospital'},
    { title: 'Bibliothek' , image: 'library'},
    { title: 'Gefängnis' , image: 'prison'},
    { title: 'Schule' , image: 'school'},
    { title: 'Piratenschiff' , image: 'ship'},
    { title: 'Taxi' , image: 'taxi'},
    { title: 'Bahnhof' , image: 'train'},
    { title: 'Toilette' , image: 'wc'},
    { title: 'Flugzeug' , image: 'airplane'},
    { title: 'Auschwitz Camp' , image: 'auschwitz'},
    { title: 'Strand' , image: 'beach'},
    { title: 'Kasino' , image: 'casino'},
    { title: 'Konzert' , image: 'concert'},
    { title: 'Everest Peak' , image: 'everest'},
    { title: 'Tankstelle' , image: 'gasstation'},
    { title: 'Wald' , image: 'jungle'},
    { title: 'Kamikaze Flugzeuge ' , image: 'kamikazi'},
    { title: 'Metro' , image: 'metro'},
    { title: 'Moschee' , image: 'mosque'},
    { title: 'Nachtclub' , image: 'nightclub'},
    { title: 'Schwimmbad' , image: 'pool'},
    { title: 'Demonstration' , image: 'protest'},
    { title: 'Südpol' , image: 'southpole'},
    { title: 'Raumstation' , image: 'spacestation'},
    { title: 'Sportstadion' , image: 'stadium'},
    { title: 'U-Boot' , image: 'submarine'},
    { title: 'Zoo' , image: 'zoo'},

] ,
spy: {title: 'Spion!' , image: 'spy'}
}