module.exports = {
    places : [{ title: 'Airport' , image: 'airport'} , 
    { title: 'Bank' , image: 'bank'},
    { title: 'Cemetery' , image: 'cemetery'},
    { title: 'Cinema' , image: 'cinema'},
    { title: 'Hell' , image: 'hell'},
    { title: 'Hospital' , image: 'hospital'},
    { title: 'Library' , image: 'library'},
    { title: 'Prison' , image: 'prison'},
    { title: 'School' , image: 'school'},
    { title: 'Pirate Ship' , image: 'ship'},
    { title: 'Taxi' , image: 'taxi'},
    { title: 'Train Station' , image: 'train'},
    { title: 'Toilette' , image: 'wc'},
    { title: 'Airplane' , image: 'airplane'},
    { title: 'Auschwitz Camp' , image: 'auschwitz'},
    { title: 'Beach' , image: 'beach'},
    { title: 'Casino' , image: 'casino'},
    { title: 'Concert' , image: 'concert'},
    { title: 'Everest Peak' , image: 'everest'},
    { title: 'Gas Station' , image: 'gasstation'},
    { title: 'Jungle' , image: 'jungle'},
    { title: 'Kamikaze Aircraft ' , image: 'kamikazi'},
    { title: 'Metro' , image: 'metro'},
    { title: 'Mosque' , image: 'mosque'},
    { title: 'Night Club' , image: 'nightclub'},
    { title: 'Pool' , image: 'pool'},
    { title: 'Demonstration' , image: 'protest'},
    { title: 'South Pole' , image: 'southpole'},
    { title: 'Space Station' , image: 'spacestation'},
    { title: 'Sport Stadium' , image: 'stadium'},
    { title: 'Submarine' , image: 'submarine'},
    { title: 'Zoo' , image: 'zoo'},

] ,
spy: {title: 'Spy!' , image: 'spy'}
}